//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmentSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Apartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apartment()
        {
            this.Contracts = new HashSet<Contract>();
        }
    
        public int AptId { get; set; }
        [DisplayName("Apt Address")]
        public string AptAddress { get; set; }
        [DisplayName("Sq. Footage")]
        public Nullable<int> SqFootage { get; set; }
        [DisplayName("Month Utility Fee")]
        [DataType(DataType.Currency)]
        public Nullable<double> MonthUtilityFee { get; set; }
        [DisplayName("Month Park Fee")]
        [DataType(DataType.Currency)]
        public Nullable<double> MonthParkfee { get; set; }
        [DisplayName("Last Clean Date")]
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> LastCleanDate { get; set; }
        [DisplayName("Vacant")]
        public bool IsVacant { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contracts { get; set; }
    }
}
