//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmentSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int ContractId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<double> MonthlyRent { get; set; }
        public int AptId { get; set; }
        public int TenantId { get; set; }
    
        public virtual Apartment Apartment { get; set; }
        public virtual Tenant Tenant { get; set; }
    }
}
